version: "2"
linters:
  default: standard
  enable:
    - depguard
    - goconst
    - godot
    - grouper
    - misspell
    - perfsprint
    - thelper
    - unconvert
    - unparam
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/traefik/yaegi
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    staticcheck:
      checks: ["all", "-ST1000", "-ST1023", "-QF1001", "-QF1008", "-QF1011"]
  exclusions:
    generated: lax
    rules:
      - linters:
          - goconst
        path: .+_test\.go
      - path: .+_test\.go
        text: 'var-declaration:'
      - path: interp/interp.go
        text: '`in` can be `io.Reader`'
      - path: interp/interp.go
        text: '`out` can be `io.Writer`'
      - path: interp/interp.go
        text: '`Panic` should conform to the `XxxError` format'
      - linters:
          - thelper
        path: interp/interp_eval_test.go
      - linters:
          - containedctx
        path: interp/debugger.go
      - path: (.+)\.go$
        text: fmt.Sprintf can be replaced with string
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
